site_name: Diffusion Models Implementation
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - content.code.copy
  icon:
    admonition:
      note: octicons/pencil-16
      tip: octicons/light-bulb-16
      warning: octicons/alert-16
      example: octicons/beaker-16
      abstract: octicons/checklist-16

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables

plugins:
  - search
  - mkdocs-simple-hooks:
      hooks:
        on_files: "docs.hooks:on_files"

extra:
  assets:
    images: assets/images

nav:
  - Home: index.md
  - Getting Started: 
    - Installation: getting_started/installation.md
    - Quick Start: getting_started/quickstart.md
  - Models:
    - Overview: models/overview.md
    - U-Net: models/unet.md
    - DiT: models/dit.md
  - Training:
    - Setup: training/setup.md
    - LoRA: training/lora.md
  - MLOps:
    - MLflow: mlops/mlflow.md
    - Deployment: mlops/deployment.md
